name: Build
on:
  push:
    branches:
      - master
      - feature/AllBuildsToAction
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual'  
jobs:
  test-untils:
    name: Utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: echo ${{ github.workspace }}
        shell: pwsh
      - id: builder
        uses: ./.github/workflows/buildtest-action
        with:
          bt-param: 'Framework/UtilitiesUnitTests/UtilitiesUnitTests.csproj --settings Framework/Parallel.RunSettings  --logger trx --results-directory "${{github.workspace}}/artifactTests/untils/" /p:CoverletOutput="${{github.workspace}}/artifactTests/untils/" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      - uses: actions/upload-artifact@v2
        name: "Upload test artifact"
        with:
          name: untilResults
          path: |
            artifactTests/untils/**/*.xml

  test-base:
    name: Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: echo ${{ github.workspace }}
        shell: pwsh
      - id: builder
        uses: ./.github/workflows/buildtest-action
        with:
          bt-param: 'Framework/BaseTestUnitTests/BaseTestUnitTests.csproj --settings Framework/Parallel.RunSettings  --logger trx --results-directory "${{github.workspace}}/artifactTests/base/" /p:CoverletOutput="${{github.workspace}}/artifactTests/base/" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      - uses: actions/upload-artifact@v2
        name: "Upload test artifact"
        with:
          name: baseResults
          path: |
            artifactTests/base/**/*.xml

 
  test-webservice:
    name: WebService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - run: echo ${{ github.workspace }}
        shell: pwsh
      - id: builder
        uses: ./.github/workflows/buildtest-action
        with:
          bt-param: 'Framework/WebServiceUnitTests/WebServiceUnitTests.csproj --settings Framework/Parallel.RunSettings  --logger trx --results-directory "${{github.workspace}}/artifactTests/webservice/" /p:CoverletOutput="${{github.workspace}}/artifactTests/webservice/" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
      - uses: actions/upload-artifact@v2
        name: "Upload test artifact"
        with:
          name: webserviceResults
          path: |
            artifactTests/webservice/**/*.xml

   
  test-mongo:
    name: Mongo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build the docker-compose stack
        run: docker-compose -f Docker/MAQSMongoDB/docker-compose.yml -p Magenic/MAQS up -d
      - run: echo ${{ github.workspace }}
        shell: pwsh
      - id: builder
        uses: ./.github/workflows/buildtest-action
        with:
          bt-param: 'Framework/MongoDBUnitTests/MongoDBUnitTests.csproj  --settings Framework/Parallel.RunSettings   --logger trx --results-directory "${{github.workspace}}/artifactTests/mongo/" /p:CoverletOutput="${{github.workspace}}/artifactTests/mongo/"  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover' 
          artifact-name: 'utils'
      - run: echo random-numberz ${{ steps.builder.outputs.random-number }}
        shell: pwsh
      - uses: actions/upload-artifact@v2
        name: "Upload test artifact"
        with:
          name: mongoResults
          path: |
            artifactTests/mongo/**/*.xml


  test-database:
    name: Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build the docker-compose stack
        run: docker-compose -f Docker/MAQSSQLServer/docker-compose.yml -p Magenic/MAQS up -d
      - run: echo ${{ github.workspace }}
        shell: pwsh
      - id: builder
        uses: ./.github/workflows/buildtest-action
        with:
          bt-param: 'Framework/DatabaseUnitTests/DatabaseUnitTests.csproj  --settings Framework/Parallel.RunSettings   --logger trx --results-directory "${{github.workspace}}/artifactTests/database/" /p:CoverletOutput="${{github.workspace}}/artifactTests/database/"  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover' 
          artifact-name: 'utils'
      - run: echo random-numberz ${{ steps.builder.outputs.random-number }}
        shell: pwsh
      - uses: actions/upload-artifact@v2
        name: "Upload test artifact"
        with:
          name: databaseResults
          path: |
            artifactTests/database/**/*.xml
            artifactTests/database/**/*.trx

  sonar:
    name: Sonar
    runs-on: windows-latest
    needs: [test-untils, test-mongo, test-database, test-webservice, test-base]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/Results
          
      - name: Update coverage mappings
        shell: powershell
        run: |
          $rootPath = "${{ github.workspace }}/Results"
          $sourcePath = "${{ github.workspace }}"

          Write-Host "Start"

          Function Replace($path, $pattern, $replace)
          {
          Write-Host $path, 
          Write-Host $pattern
          Write-Host $replace

              $text = (Get-Content $path) -join "`n"
              [System.Text.RegularExpressions.Regex]::Replace($text, $pattern, $replace) |  Out-File -encoding ASCII $path

          }

          $files = Get-ChildItem -Path $rootPath -Recurse -Include *.xml
          foreach ($file in $files)
          {
              Replace $file.FullName '(?<=fullPath=")(([\w\d\s/\\:]+)(?=[\\/][Ff]ramework))' $sourcePath 
              Replace $file.FullName '(?<=fullPath="[\w\d\s/.\\:]+)((/)(?=[\w\d\s/.]+"))' "\"
          }

          $files = Get-ChildItem -Path $rootPath  -Recurse  -Include *.trx
          foreach ($file in $files)
          {
              Replace $file.FullName '(?<=codeBase=")(([\w\d\s/\\:]+)(?=[\\/][Ff]ramework))' $sourcePath
              Replace $file.FullName '(?<=codeBase="[\w\d\s/.\\:]+)((/)(?=[\w\d\s/.]+"))' "\"
              Replace $file.FullName '(?<=storage=")(([\w\d\s/\\:]+)(?=[\\/][Ff]ramework))' $sourcePath.ToLower()
              Replace $file.FullName '(?<=storage="[\w\d\s/.\\:]+)((/)(?=[\w\d\s/.]+"))' "\"
          }

          Write-Host "End"
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"MAQS" /o:"magenic" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=${{ github.workspace }}\Results\**\coverage.opencover.xml  /d:sonar.cs.dotcover.reportsPaths=${{ github.workspace }}\Results\**\*.coverage
          dotnet build Framework/Base.sln
          # dotnet test Framework/UtilitiesUnitTests/UtilitiesUnitTests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
